  
version: '3'

services:

    webapi:
        depends_on: 
           - redis # This service depends on redis. Start that first.
        links:
            - redis
        build: .
        command: go run main.go
        ports:
            - "8080:8080"
        networks:
            - backend

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
           - ./data:/data
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        
        networks:
           - backend

networks:
        backend: