  
version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        expose:
            - 8080
        depends_on: 
            - redis

services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
           - ./data:/data
        command:  redis-server --appendonly yes